name: README Scribe

on:
  workflow_dispatch: # manual trigger via GitHub UI
  schedule:
    - cron: '0 0 * * *' # daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run readme-scribe
        uses: charmbracelet/readme-scribe@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_URL: ${{ secrets.WAKATIME_URL }}

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "🤖 Update README with readme-scribe" || echo "No changes to commit"
          git push
