name: Update README with Coding Stats
on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch: # Allow manual trigger
jobs:
  update-readme:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Fetch and update WakaTime stats
        run: |
          python -c "
          import requests
          import re
          import os

          # Fetch stats from API
          api_url = '${{ secrets.API_BASE_URL }}/users/current/stats/last_7_days'
          headers = {'Authorization': '${{ secrets.API_KEY }}', 'User-Agent': 'Mozilla/5.0'}
          response = requests.get(api_url, headers=headers)
          response.raise_for_status()
          data = response.json()['data']

          # Format stats as Markdown
          total_time = data['human_readable_total']
          languages = '\n'.join(f'- {lang['name']}: {lang['text']} ({lang['percent']}%)' for lang in data['languages'][:8])
          projects = '\n'.join(f'- {proj['name']}: {proj['text']} ({proj['percent']}%)' for proj in data['projects'][:5])
          stats_content = f'''## Coding Stats
          Total Time: {total_time}
          
          **Languages:**
          {languages}
          
          **Projects:**
          {projects}
          '''

          # Read README
          with open('README.md', 'r') as file:
              content = file.read()

          # Replace content between markers
          new_content = re.sub(
              r'<!--START_SECTION:waka-->\n.*?<!--END_SECTION:waka-->\n',
              f'<!--START_SECTION:waka-->\n{stats_content}<!--END_SECTION:waka-->\n',
              content,
              flags=re.DOTALL
          )

          # Write updated README
          with open('README.md', 'w') as file:
              file.write(new_content)
          "
      - name: Commit changes
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            execSync('git config user.name "GitHub Actions"');
            execSync('git config user.email "actions@github.com"');
            execSync('git add README.md');
            try {
              execSync('git commit -m "Update README with coding stats"');
              execSync('git push');
            } catch (error) {
              console.log('No changes to commit');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
