name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Test Hackatime API
        run: |
          echo "Testing with Bearer auth"
          curl -v -X GET "${{ secrets.WAKATIME_URL }}/users/current/stats/last_7_days" \
               -H "Authorization: Bearer ${{ secrets.WAKATIME_API_KEY }}" \
               -H "User-Agent: Mozilla/5.0" \
               -o response_bearer.json || echo "Bearer cURL failed with exit code $?"
          if [ -f response_bearer.json ]; then
            cat response_bearer.json
            jq . response_bearer.json || echo "Bearer JSON parsing failed"
          else
            echo "No Bearer response file created"
          fi
          echo "Testing with Basic auth"
          encoded_key=$(echo -n "${{ secrets.WAKATIME_API_KEY }}" | base64)
          curl -v -X GET "${{ secrets.WAKATIME_URL }}/users/current/stats/last_7_days" \
               -H "Authorization: Basic $encoded_key" \
               -H "User-Agent: Mozilla/5.0" \
               -o response_basic.json || echo "Basic cURL failed with exit code $?"
          if [ -f response_basic.json ]; then
            cat response_basic.json
            jq . response_basic.json || echo "Basic JSON parsing failed"
          else
            echo "No Basic response file created"
          fi
        continue-on-error: true
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          API_BASE_URL: ${{ secrets.WAKATIME_URL }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          TIME_RANGE: last_7_days
          LANG_COUNT: 8
          SHOW_TIME: true
          SHOW_TOTAL: true
